CREATE TABLE VOL (
  ID INT NOT NULL PRIMARY KEY,
  USERNAME VARCHAR(30) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  NAME VARCHAR(30) NOT NULL,
  SURNAME VARCHAR(30) NOT NULL,
  SECOND_SURNAME VARCHAR(30),
  BIRTHDAY DATE,
  EXP INT DEFAULT '0' NOT NULL,
  LVL INT DEFAULT '0' NOT NULL,
  ACCOUNT_EXPIRED BOOLEAN NOT NULL DEFAULT FALSE,
  ACCOUNT_LOCKED BOOLEAN NOT NULL DEFAULT FALSE,
  CREDENTIALS_EXPIRED BOOLEAN NOT NULL DEFAULT FALSE,
  ACCOUNT_ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
  DATE_CREATED DATE NOT NULL,
  DATE_MODIFIED DATE
);
  
CREATE TABLE ONG (
  ID INT NOT NULL PRIMARY KEY,
  USERNAME VARCHAR(30) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(800) NOT NULL,
  ADDRESS VARCHAR(150),
  CV_REQUIRED BOOLEAN NOT NULL DEFAULT FALSE,
  ACCOUNT_EXPIRED BOOLEAN NOT NULL DEFAULT FALSE,
  ACCOUNT_LOCKED BOOLEAN NOT NULL DEFAULT FALSE,
  CREDENTIALS_EXPIRED BOOLEAN NOT NULL DEFAULT FALSE,
  ACCOUNT_ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
  DATE_CREATED DATE NOT NULL,
  DATE_MODIFIED DATE DEFAULT NULL
);
  
CREATE TABLE EVNT (
  ID INT PRIMARY KEY NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  EVNT_DATE DATE NOT NULL,
  EVNT_TIME VARCHAR(5) NOT NULL,
  ONG_ID INT NOT NULL,
  DESCRIPTION VARCHAR(800) NOT NULL,
  ADDRESS VARCHAR(100) NOT NULL,
  LAT VARCHAR(12) DEFAULT NULL,
  LNG VARCHAR(12) DEFAULT NULL,
  DATE_CREATED DATE NOT NULL,
  DATE_MODIFIED DATE DEFAULT NULL
);
  
CREATE TABLE ONG_VOL (
  ONG_ID INT NOT NULL,
  VOL_ID INT NOT NULL
);
  
CREATE TABLE EVNT_VOL (
  EVNT_ID INT NOT NULL,
  VOL_ID INT NOT NULL
);
  
CREATE TABLE ROLE (
  ID INT NOT NULL PRIMARY KEY,
  NAME VARCHAR(30) NOT NULL --ONG, VOL, ADMIN?
);

ALTER TABLE EVNT ADD CONSTRAINT EVNT_ONG_FK FOREIGN KEY ( ONG_ID ) REFERENCES ONG ( ID );

ALTER TABLE ONG_VOL ADD CONSTRAINT ONG_VOL_ONG_FK FOREIGN KEY ( ONG_ID ) REFERENCES ONG ( ID );
ALTER TABLE ONG_VOL ADD CONSTRAINT ONG_VOL_VOL_FK FOREIGN KEY ( VOL_ID ) REFERENCES VOL ( ID );

ALTER TABLE EVNT_VOL ADD CONSTRAINT EVNT_VOL_EVNT_FK FOREIGN KEY ( EVNT_ID ) REFERENCES EVNT ( ID );
ALTER TABLE EVNT_VOL ADD CONSTRAINT EVNT_VOL_VOL_FK FOREIGN KEY ( VOL_ID ) REFERENCES VOL( ID );